### ISSUE TITLE
[component]画面遷移ボタン(いちらん)

### ISSUE THREAD

**Issue by ChiekoIshii** [yutaroyoshikawa/rinne#9]
<img width="264" alt="スクリーンショット 2020-10-21 12 04 41" src="https://user-images.githubusercontent.com/39544110/96668212-9b361600-1395-11eb-9fc8-3f6ed88623d1.png">

## ベース
- W:100/H:100
- 929D49

## 文字
- 18px
- #F3EBD8
- 上下左右中央寄せ

**Comment by chinkonhi** [comment]
ボダンのデザインをお願いします
